### ISSUE TITLE
Ordered List not being rendered

### ISSUE THREAD

**Issue by sheonhan** [nishanths/cocoa-hugo-theme#87] opened 2017-05-28 16:04 UTC
When I write in Markdown:
```
1. One
2. Two 
3. Three
```

It gets rendered as:
- One
- Two 
- Three

I tried this theme on a newly created site and the behavior persists. Could you help me with this issue?

**Comment by felixthoemmes** [comment] 2017-05-31 13:17
I am using RMarkdown, so maybe it's a bit different, but I had the same issue. 
Currently, I use the workaround

1.) One  
2.) Two  
3.) Three  

but this shows up as:

<p>1.) Pre-register your analyses and report the results of your pre-registration fully<br />
2.) If you decide to run an unregistered analysis, mark it as exploratory</p>

So also not a list, but at least it looks as intended.

**Comment by nishanths** [comment] 2017-10-16 12:09
thanks! fixed in ded90f8

**Closed as completed by nishanths** 2017-10-16 12:09 UTC
